import { NextResponse } from "next/server";
import { ensureSchema, getPool } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";

/**
 * POST /api/admin/workshops/deactivate
 * 
 * Deactivates all workshop deliverables from the catalog
 * Workshops are now generated by AI, not selected from catalog
 * 
 * Admin-only endpoint
 */
export async function POST() {
  try {
    await ensureSchema();
    const pool = getPool();
    
    // Verify user is admin
    const currentUser = await getCurrentUser();
    if (!currentUser?.isAdmin) {
      return NextResponse.json({ error: "Admin access required" }, { status: 403 });
    }

    // Deactivate all workshop deliverables
    const result = await pool.query(
      `UPDATE deliverables
       SET active = false,
           updated_at = NOW()
       WHERE deliverable_type = 'workshop'
       RETURNING id, name`,
    );

    const deactivatedWorkshops = result.rows.map((row) => ({
      id: row.id,
      name: row.name,
    }));

    return NextResponse.json({
      success: true,
      message: `Deactivated ${deactivatedWorkshops.length} workshop deliverables`,
      workshops: deactivatedWorkshops,
    });

  } catch (error: unknown) {
    console.error("Error deactivating workshops:", error);
    return NextResponse.json(
      { error: (error as Error).message ?? "Unknown error" },
      { status: 500 }
    );
  }
}

/**
 * DELETE /api/admin/workshops/deactivate
 * 
 * Reactivates all workshop deliverables (in case you need to rollback)
 */
export async function DELETE() {
  try {
    await ensureSchema();
    const pool = getPool();
    
    // Verify user is admin
    const currentUser = await getCurrentUser();
    if (!currentUser?.isAdmin) {
      return NextResponse.json({ error: "Admin access required" }, { status: 403 });
    }

    // Reactivate all workshop deliverables
    const result = await pool.query(
      `UPDATE deliverables
       SET active = true,
           updated_at = NOW()
       WHERE deliverable_type = 'workshop'
       RETURNING id, name`,
    );

    const reactivatedWorkshops = result.rows.map((row) => ({
      id: row.id,
      name: row.name,
    }));

    return NextResponse.json({
      success: true,
      message: `Reactivated ${reactivatedWorkshops.length} workshop deliverables`,
      workshops: reactivatedWorkshops,
    });

  } catch (error: unknown) {
    console.error("Error reactivating workshops:", error);
    return NextResponse.json(
      { error: (error as Error).message ?? "Unknown error" },
      { status: 500 }
    );
  }
}

