import { getCurrentUser } from "@/lib/auth";
import { redirect } from "next/navigation";
import WorkshopCleanupClient from "./WorkshopCleanupClient";

export const dynamic = "force-dynamic";

export default async function WorkshopCleanupPage() {
  const user = await getCurrentUser();
  
  if (!user?.isAdmin) {
    redirect("/");
  }

  return (
    <main className="min-h-screen max-w-4xl mx-auto p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-bold mb-2">Workshop Cleanup</h1>
        <p className="text-sm opacity-70">
          Remove workshop deliverables from packages and delete them from the system.
          Workshops are now generated by AI, not selected from catalog.
        </p>
      </div>

      <WorkshopCleanupClient />
    </main>
  );
}

