"use client";

import { useState } from "react";

type PreviewData = {
  workshops: Array<{
    id: string;
    name: string;
    category: string;
    hours: number;
    price: number;
  }>;
  affectedPackages: number;
  affectedSprints: number;
  packageNames: string[];
};

type CleanupResult = {
  removed: {
    fromPackages: number;
    fromSprints: number;
    deliverables: number;
  };
  deletedWorkshops: string[];
};

export default function WorkshopCleanupClient() {
  const [preview, setPreview] = useState<PreviewData | null>(null);
  const [result, setResult] = useState<CleanupResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handlePreview = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const res = await fetch("/api/admin/workshops/cleanup");
      const data = await res.json();
      
      if (!res.ok) {
        throw new Error(data.error || "Failed to preview");
      }
      
      setPreview(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to preview");
    } finally {
      setLoading(false);
    }
  };

  const handleCleanup = async () => {
    if (!confirm("Are you sure you want to delete all workshop deliverables? This cannot be undone.")) {
      return;
    }

    setLoading(true);
    setError(null);
    
    try {
      const res = await fetch("/api/admin/workshops/cleanup", {
        method: "POST",
      });
      const data = await res.json();
      
      if (!res.ok) {
        throw new Error(data.error || "Failed to cleanup");
      }
      
      setResult(data);
      setPreview(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to cleanup");
    } finally {
      setLoading(false);
    }
  };

  if (result) {
    return (
      <div className="space-y-6">
        <div className="rounded-lg bg-green-50 dark:bg-green-950/30 border border-green-200 dark:border-green-800 p-6">
          <div className="flex items-center gap-3 mb-4">
            <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
            </svg>
            <h2 className="text-xl font-bold text-green-900 dark:text-green-100">
              Cleanup Complete!
            </h2>
          </div>

          <div className="space-y-3 text-sm">
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white dark:bg-black/40 rounded p-3">
                <div className="text-xs opacity-70 mb-1">Removed from Packages</div>
                <div className="text-2xl font-bold text-green-700 dark:text-green-300">
                  {result.removed.fromPackages}
                </div>
              </div>
              <div className="bg-white dark:bg-black/40 rounded p-3">
                <div className="text-xs opacity-70 mb-1">Removed from Sprints</div>
                <div className="text-2xl font-bold text-green-700 dark:text-green-300">
                  {result.removed.fromSprints}
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-black/40 rounded p-3">
              <div className="text-xs opacity-70 mb-1">Deliverables Deleted</div>
              <div className="text-2xl font-bold text-green-700 dark:text-green-300 mb-2">
                {result.removed.deliverables}
              </div>
              <ul className="space-y-1 text-xs">
                {result.deletedWorkshops.map((name, i) => (
                  <li key={i} className="opacity-70">• {name}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="mt-4 pt-4 border-t border-green-200 dark:border-green-800">
            <p className="text-sm text-green-800 dark:text-green-200">
              ✅ All workshop deliverables have been removed from the system.
              Workshops will now be generated by AI for each sprint.
            </p>
          </div>
        </div>

        <button
          onClick={() => {
            setResult(null);
            setPreview(null);
          }}
          className="px-4 py-2 bg-gray-200 dark:bg-gray-800 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-700 transition"
        >
          Done
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {!preview ? (
        <div className="rounded-lg border-2 border-dashed border-gray-300 dark:border-gray-700 p-8 text-center">
          <div className="mb-4">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-purple-100 dark:bg-purple-900/30 mb-4">
              <span className="text-3xl">🧹</span>
            </div>
            <h3 className="text-lg font-semibold mb-2">Clean Up Workshop Deliverables</h3>
            <p className="text-sm opacity-70 mb-6">
              This will preview which workshops will be removed from packages and deleted from the system.
            </p>
          </div>

          <button
            onClick={handlePreview}
            disabled={loading}
            className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition font-semibold"
          >
            {loading ? "Loading..." : "Preview Cleanup"}
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="rounded-lg border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-950/20 p-6">
            <div className="flex items-start gap-3 mb-4">
              <svg className="w-6 h-6 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              <div className="flex-1">
                <h3 className="font-bold text-yellow-900 dark:text-yellow-100 mb-2">
                  Review Changes Before Proceeding
                </h3>
                <p className="text-sm text-yellow-800 dark:text-yellow-200">
                  This is a destructive operation. Workshop deliverables will be permanently deleted.
                </p>
              </div>
            </div>

            {preview.workshops.length === 0 ? (
              <div className="text-sm text-yellow-800 dark:text-yellow-200">
                ✅ No workshop deliverables found. System is already clean!
              </div>
            ) : (
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white dark:bg-black/40 rounded p-3">
                    <div className="text-xs opacity-70 mb-1">Workshops to Delete</div>
                    <div className="text-2xl font-bold">{preview.workshops.length}</div>
                  </div>
                  <div className="bg-white dark:bg-black/40 rounded p-3">
                    <div className="text-xs opacity-70 mb-1">Packages Affected</div>
                    <div className="text-2xl font-bold">{preview.affectedPackages}</div>
                  </div>
                </div>

                {preview.affectedSprints > 0 && (
                  <div className="bg-red-100 dark:bg-red-900/30 rounded p-3">
                    <div className="text-xs font-semibold text-red-800 dark:text-red-200 mb-1">
                      ⚠️ Active Sprints Using Workshops
                    </div>
                    <div className="text-2xl font-bold text-red-700 dark:text-red-300">
                      {preview.affectedSprints}
                    </div>
                    <p className="text-xs text-red-700 dark:text-red-300 mt-2">
                      These sprints have workshop deliverables that will be removed.
                    </p>
                  </div>
                )}

                <div>
                  <h4 className="text-sm font-semibold mb-2">Workshops to be deleted:</h4>
                  <div className="space-y-2">
                    {preview.workshops.map((workshop) => (
                      <div key={workshop.id} className="bg-white dark:bg-black/40 rounded p-3 text-sm">
                        <div className="font-semibold">{workshop.name}</div>
                        <div className="text-xs opacity-70 mt-1">
                          {workshop.category} • {workshop.hours}h • ${workshop.price}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {preview.packageNames.length > 0 && (
                  <div>
                    <h4 className="text-sm font-semibold mb-2">Affected packages:</h4>
                    <div className="space-y-1">
                      {preview.packageNames.map((name, i) => (
                        <div key={i} className="text-sm opacity-70">• {name}</div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="flex gap-3">
            <button
              onClick={handleCleanup}
              disabled={loading || preview.workshops.length === 0}
              className="flex-1 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition font-semibold"
            >
              {loading ? "Cleaning Up..." : "Confirm & Delete Workshops"}
            </button>
            <button
              onClick={() => setPreview(null)}
              disabled={loading}
              className="px-6 py-3 bg-gray-200 dark:bg-gray-800 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-700 disabled:opacity-50 transition"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {error && (
        <div className="rounded-lg bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 p-4">
          <div className="flex items-center gap-2">
            <svg className="w-5 h-5 text-red-600 dark:text-red-400" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
            </svg>
            <p className="text-red-800 dark:text-red-200 text-sm">{error}</p>
          </div>
        </div>
      )}
    </div>
  );
}

